version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/db.sqlite:/app/db.sqlite
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 