@echo off
echo Installing root dependencies (including concurrently)...
npm install
echo Installing backend dependencies...
npm install --prefix backend
echo Installing frontend dependencies...
npm install --prefix frontend
echo Starting backend and frontend concurrently...
npm start 